[server]
headless = true
port = 8501

[theme]
base = "light"
primaryColor = "#D94F4F"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#3A2E1F"
font = "sans serif"

[browser]
gatherUsageStats = false
